// This file is auto-generated by @hey-api/openapi-ts

export const JsonObjectSchema = {
  title: "JsonObject",
  type: "object",
} as const;

export const ProblemSchema = {
  title: "Problem",
  required: ["status", "title"],
  type: "object",
  properties: {
    status: {
      type: "integer",
      description: "HTTP response status code.",
      format: "int32",
      example: 400,
    },
    title: {
      type: "string",
      description: "Error short description.",
      example: "Bad request.",
    },
    detail: {
      type: "string",
    },
    instance: {
      type: "string",
    },
  },
  description: "Represents an error of the SwissBorg Rest API.",
} as const;
