// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from "./client";
import { client } from "./client.gen";
import type {
  GenerateCertificateData,
  GenerateCertificateErrors,
  GenerateCertificateResponses,
  GetCertificateData,
  GetCertificateErrors,
  GetCertificateResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Start the generation of the ZK certificate of the authenticated user.
 *
 * This endpoint only works if the user has been verified and KYC is passed.
 * It means the user must be at least tier 1 (proof of identity) in the SwissBorg platform.
 * If the user is still in onboarding, or in recovery, this endpoint will fail with a 4xx error.
 *
 */
export const generateCertificate = <ThrowOnError extends boolean = false>(
  options: Options<GenerateCertificateData, ThrowOnError>
) => {
  return (options.client ?? client).post<
    GenerateCertificateResponses,
    GenerateCertificateErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/galactica/cert/generate",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Get the certificate for the authenticated user, if any.
 *
 */
export const getCertificate = <ThrowOnError extends boolean = false>(
  options?: Options<GetCertificateData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    GetCertificateResponses,
    GetCertificateErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/galactica/cert",
    ...options,
  });
};
