// This file is auto-generated by @hey-api/openapi-ts

export type JsonObject = {
  [key: string]: unknown;
};

/**
 * Represents an error of the SwissBorg Rest API.
 */
export type Problem = {
  /**
   * HTTP response status code.
   */
  status: number;
  /**
   * Error short description.
   */
  title: string;
  detail?: string;
  instance?: string;
};

export type GenerateCertificateData = {
  /**
   * The client parameters
   */
  body: JsonObject;
};

export type GenerateCertificateResponse = JsonObject;

export type GenerateCertificateError = string | Problem;

export type GetCertificateResponse = JsonObject;

export type GetCertificateError = Problem;
