// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl:
    | "https://api-stage.swissborg.io/v1"
    | "https://api.swissborg.io/v1"
    | (string & {});
};

/**
 * JsonObject
 */
export type JsonObject = {
  [key: string]: unknown;
};

/**
 * Problem
 * Represents an error of the SwissBorg Rest API.
 */
export type Problem = {
  /**
   * HTTP response status code.
   */
  status: number;
  /**
   * Error short description.
   */
  title: string;
  detail?: string;
  instance?: string;
};

export type GenerateCertificateData = {
  /**
   * The client parameters
   */
  body: JsonObject;
  path?: never;
  query?: never;
  url: "/galactica/cert/generate";
};

export type GenerateCertificateErrors = {
  /**
   * Invalid value for: body
   */
  400: string;
  default: Problem;
};

export type GenerateCertificateError =
  GenerateCertificateErrors[keyof GenerateCertificateErrors];

export type GenerateCertificateResponses = {
  200: JsonObject;
};

export type GenerateCertificateResponse =
  GenerateCertificateResponses[keyof GenerateCertificateResponses];

export type GetCertificateData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/galactica/cert";
};

export type GetCertificateErrors = {
  default: Problem;
};

export type GetCertificateError =
  GetCertificateErrors[keyof GetCertificateErrors];

export type GetCertificateResponses = {
  200: JsonObject;
};

export type GetCertificateResponse =
  GetCertificateResponses[keyof GetCertificateResponses];
