// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl:
    | "https://api-stage.swissborg.io/v1"
    | "https://api.swissborg.io/v1"
    | (string & {});
};

/**
 * Approved
 */
export type Approved = {
  code: WebSessionCode;
  session_token: Jwt;
};

/**
 * JWT
 */
export type Jwt = string;

/**
 * NotFound
 */
export type NotFound = {
  code: WebSessionCode;
};

/**
 * Pending
 */
export type Pending = {
  code: WebSessionCode;
  expires_at: string;
};

/**
 * PendingApproval
 */
export type PendingApproval = {
  code: WebSessionCode;
  expires_at: string;
  device_name?: string;
};

/**
 * Problem
 * Represents an error of the SwissBorg Rest API.
 */
export type Problem = {
  /**
   * HTTP response status code.
   */
  status: number;
  /**
   * Error short description.
   */
  title: string;
  detail?: string;
  instance?: string;
};

/**
 * Rejected
 */
export type Rejected = {
  code: WebSessionCode;
};

/**
 * Secret
 * Secret value used to initiate and query the status of a Web Session flow.
 */
export type Secret = string;

/**
 * Timeout
 */
export type Timeout = {
  code: WebSessionCode;
};

/**
 * WebAuthClient
 * Target client to which the WebSession being setup is aimed for. Partners will know this value during integration phase.
 */
export type WebAuthClient = string;

/**
 * WebAuthManagementGetSessionStatusRequestBody
 */
export type WebAuthManagementGetSessionStatusRequestBody = {
  secret: Secret;
};

/**
 * WebAuthManagementGetSessionStatusResponse
 */
export type WebAuthManagementGetSessionStatusResponse =
  | {
      approved: Approved;
    }
  | {
      not_found: NotFound;
    }
  | {
      pending: Pending;
    }
  | {
      pending_approval: PendingApproval;
    }
  | {
      rejected: Rejected;
    }
  | {
      timeout: Timeout;
    };

/**
 * WebAuthManagementSetupSessionRequestBody
 */
export type WebAuthManagementSetupSessionRequestBody = {
  audience: WebAuthClient;
  secret: Secret;
};

/**
 * WebAuthManagementSetupSessionResponse
 */
export type WebAuthManagementSetupSessionResponse = {
  code: WebSessionCode;
  expires_at: string;
};

/**
 * WebSessionCode
 * Web Session flow identifier.
 */
export type WebSessionCode = string;

export type InitiateWebSessionData = {
  body: WebAuthManagementSetupSessionRequestBody;
  path?: never;
  query?: never;
  url: "/web-auth/session/setup";
};

export type InitiateWebSessionErrors = {
  /**
   * Invalid value, Invalid value for: body
   */
  400: string;
  default: Problem;
};

export type InitiateWebSessionError =
  InitiateWebSessionErrors[keyof InitiateWebSessionErrors];

export type InitiateWebSessionResponses = {
  200: WebAuthManagementSetupSessionResponse;
};

export type InitiateWebSessionResponse =
  InitiateWebSessionResponses[keyof InitiateWebSessionResponses];

export type GetWebSessionStatusData = {
  body: WebAuthManagementGetSessionStatusRequestBody;
  path: {
    code: WebSessionCode;
  };
  query?: never;
  url: "/web-auth/session/status/{code}";
};

export type GetWebSessionStatusErrors = {
  /**
   * Invalid value for: body
   */
  400: string;
  default: Problem;
};

export type GetWebSessionStatusError =
  GetWebSessionStatusErrors[keyof GetWebSessionStatusErrors];

export type GetWebSessionStatusResponses = {
  200: WebAuthManagementGetSessionStatusResponse;
};

export type GetWebSessionStatusResponse =
  GetWebSessionStatusResponses[keyof GetWebSessionStatusResponses];
